# In production environment the config server uses a keystore or vault to protect password.
#    spring.security.user.password: '{cipher}AQBEBfqLmGyuR5sfmNf98rw0cFrFmWA8iUbafn4XhK6vMjQ9tTxAwXRm3fEAE49h7r3dlmHgBk9trPai5tcoJfiOeDGdLUPgTMXphesVT6CH0du3nvJZqGqSROy/8TwSvnjr6Uz3pO57jT+uESrYg4/BE2l2HIZT59qJUG/yvCZiqTiqovj9YEEVa4kI5bW8HiBDS5o5Oq/1+8LmrSTZlb/ui9JPxIOd/XuI0NT7uPb7mstS4x+/65DxoGMVsRUA87SkPN+/YYbBdxFOV4jmv/RzlK+sEp0fqu82OEYCFRUdB9mpH+UWD6GcsNPfjM5uT7slaPTAuElhFjZ4vAUQjggb77NCuyyopakRmfIEz7eTjCMB/2pBoekwM5YPm2RgCyI='

spring:
  jpa:
    database: postgresql
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://openwms-postgresql.automatic-warehouse.svc.cluster.local:5432/RBDB
    username: KARL
    password: KARL
